# Generated by Django 4.0.4 on 2022-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'AC_Owner'), (2, 'Manager'), (3, 'Staff'), (4, 'Customer')], null=True),
        ),
    ]
