# Generated by Django 4.0.4 on 2022-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'AC_Owner'), (2, 'Manager'), (3, 'Staff'), (4, 'Customer')], null=True),
        ),
    ]
