# Generated by Django 4.0.4 on 2022-05-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_brand_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='app.menu'),
        ),
    ]
